"""
Detection Pipeline Requirements

1. Subject - A subject defines the features (pixels/bytes) to detect instances of itself in frame pixel data

2. Detector - A Detector loads a Subject to detect and reads Frames generated by Streams. It uses the Subject.features to findRawDetections. It creates Events 
                based on the raw detection data, which are then passed into the Event Processor.

3. Event - The Event class defines a structure of an event for a given Subject. It requires the source Stream and the detection Timestamp to create a time
            series event of a detection instance.

4. Event Processor - The Event Processor accepts events as they are created then decides how to handle them. It may have zero or more Reporters attached and 
                     will notify() each Reporter when event processing is complete.

5. Reporter - The Event Processor calls notify(), which triggers the update() method on each attached Reporter. The Reporter is responsible for sinking the
              time series events to the data storage layer.
"""
import os
import sys


sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))